baseURL = "https://cooking.tiago.life/"
languageCode = "en-uk"
title = "My Cooking Book - Tiago Queiroz"
theme = "gochowdown"
# paginate= 20
canonifyurls= true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Tiago Queiroz"

[params]
  hidecredits = false
  hidecopyright = false
  showNavTitle = true

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # metadata for HTML
  description = "Coocking site of Tiago Queiroz"
  footercontent = "Recipes for the home cook."
  # keywords = ""

  # Top menu
  [[menu.main]]
    identifier = "Home"
    name       = "Home"
    url        = "/"
    weight = 1.0

  [[menu.main]]
    identifier = "Categories"
    name       = "Categories"
    url        = "/category/"
    weight = 2.0

  [[menu.main]]
    identifier = "Tags"
    name       = "Tags"
    url        = "/tags/"
    weight = 4.0

[taxonomies]
category = "category"
cusine = "cuisine"
tag = "tags"
meal = "Meal"



